from typing import Optional, List, Dict, Any
from typing_extensions import TypedDict


class GraphState(TypedDict):
    """Represents the complete enterprise BI graph state across execution pipelines.

    Attributes:
    question: The original user query or prompt provided as input to the pipeline.
    sql_query: The raw SQL statement dynamically generated by the text-to-SQL engine.
    sql_data: The raw tabular records returned from executing the SQL query against the database (list of dicts/tuples).
    rag_data: Unstructured customer reviews and semantic feedback retrieved from Qdrant vector storage (formatted text).
    web_data: Relevant excerpts and external market context retrieved via the Tavily/web search engine.
    reasoning_steps: Sequential execution logs, sub-inquiry findings, and intermediate diagnostic deductions gathered during multi-step execution.
    generation: The synthesized final response, data analysis, or structured executive briefing generated by the LLM.
    retry_count: An execution counter tracking fallback and regeneration attempts to prevent infinite recursion loops during hallucination or relevance corrections.
    """

    question: str

    sql_query: Optional[str]
    sql_data: Optional[Any]

    rag_query: Optional[str]
    rag_data: Optional[str]

    web_query: Optional[str]
    web_data: Optional[str]

    reasoning_steps: Optional[str]

    generation: Optional[str]
    retry_count: int